name: GitHub-Actions-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first Actions Trial"
      - run: chmod +x hello.sh
      - run: chmod + world-test.sh
      - run: ./world-test.sh
