name: GitHub-Actions-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission
        run: chmod +x hello.sh
        run: chmod + world-test.sh
      - name: Test Run
        run: ./world-test.sh
